import { ArrowUpRight, Bot, CircleCheck, Clock3, MessageSquare, RefreshCw, UserRound } from 'lucide-react';
import { Link } from 'wouter';
import { useListHelpdeskActivity } from '@workspace/api-client-react';
import { EmptyState, ErrorState, relativeTime, SectionLabel, SkeletonRows } from '@/components/helpdesk-ui';

const iconFor = (type: string) => type.toLowerCase().includes('assign') ? UserRound : type.toLowerCase().includes('resolve') ? CircleCheck : type.toLowerCase().includes('diagnos') ? Bot : MessageSquare;

export default function Activity() {
  const activity = useListHelpdeskActivity();
  return (
    <div className="animate-rise-in space-y-7">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><SectionLabel>Operations / trail</SectionLabel><h1 className="text-[clamp(1.8rem,4vw,2.65rem)] font-extrabold tracking-[-.06em]">Activity log</h1><p className="mt-2 max-w-lg text-sm text-muted-foreground">A quiet record of the decisions, handoffs, and resolutions moving through Northstar.</p></div><button onClick={() => activity.refetch()} className="inline-flex w-fit items-center gap-2 rounded-xl border border-border bg-card px-4 py-3 text-xs font-bold transition-colors hover:bg-secondary" data-testid="button-refresh-activity"><RefreshCw size={14} className={activity.isFetching ? 'animate-spin' : ''} /> Refresh trail</button></div>
      <div className="grid gap-5 lg:grid-cols-[1fr_300px]">
        <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b border-border/70 px-5 py-5 sm:px-6"><div><h2 className="text-sm font-extrabold">Recent movement</h2><p className="mt-1 text-xs text-muted-foreground">Latest actions appear here automatically.</p></div><span className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-foreground">{activity.data?.length ?? '—'} events</span></div>{activity.isLoading ? <SkeletonRows count={6} /> : activity.isError ? <ErrorState onRetry={() => activity.refetch()} /> : activity.data?.length ? <div className="divide-y divide-border/70">{activity.data.map((item, index) => { const Icon = iconFor(item.type); return <div key={item.id} className={`group flex gap-4 px-5 py-5 transition-colors hover:bg-secondary/35 sm:px-6 ${index === 0 ? 'bg-primary/[.025]' : ''}`} data-testid={`row-activity-${item.id}`}><div className="relative flex flex-col items-center"><span className={`grid size-9 place-items-center rounded-xl ${index === 0 ? 'bg-primary/10 text-primary' : 'bg-secondary text-muted-foreground'}`}><Icon size={16} /></span>{index < (activity.data?.length || 0) - 1 && <span className="mt-2 w-px flex-1 bg-border/80" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] uppercase tracking-[.1em] text-primary">{item.type}</span><span className="text-border">·</span><span className="inline-flex items-center gap-1 font-mono text-[10px] text-muted-foreground"><Clock3 size={11} />{relativeTime(item.createdAt)}</span></div><p className="mt-2 text-sm font-semibold leading-relaxed">{item.message}</p><div className="mt-2 flex items-center gap-2 text-[11px] text-muted-foreground"><span className="grid size-5 place-items-center rounded-full bg-secondary font-mono text-[8px] font-bold">{item.actor.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span>{item.actor}{item.ticketId && <Link href={`/tickets/${item.ticketId}`} className="ml-1 inline-flex items-center gap-1 font-mono text-primary hover:underline" data-testid={`link-activity-ticket-${item.id}`}>NS-{String(item.ticketId).padStart(4, '0')}<ArrowUpRight size={11} /></Link>}</div></div></div> })}</div> : <EmptyState title="No movement yet" detail="When a ticket changes hands or gets resolved, it will appear here." />}</div>
        <aside className="h-fit rounded-2xl border border-border bg-sidebar p-5 text-sidebar-foreground shadow-sm sm:p-6"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.16em] text-sidebar-primary"><span className="size-1.5 rounded-full bg-sidebar-primary animate-pulse-line" /> Activity signal</div><h2 className="mt-5 text-xl font-extrabold tracking-[-.04em]">A clear trail<br />builds trust.</h2><p className="mt-3 text-xs leading-relaxed text-sidebar-foreground/55">Every handoff is visible, so your team can spend less time asking what happened and more time fixing what matters.</p><div className="mt-7 border-t border-sidebar-border pt-4"><div className="flex items-center justify-between text-xs"><span className="text-sidebar-foreground/55">Tracking status</span><span className="inline-flex items-center gap-1.5 font-mono text-[10px] text-sidebar-primary"><span className="size-1.5 rounded-full bg-sidebar-primary" /> ACTIVE</span></div></div></aside>
      </div>
    </div>
  );
}