import { useMemo, useState } from 'react';
import { Download, Filter, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import { Link } from 'wouter';
import { getListTicketsQueryKey, useListTickets } from '@workspace/api-client-react';
import { EmptyState, ErrorState, SectionLabel, SkeletonRows, TicketRow } from '@/components/helpdesk-ui';

export default function Tickets() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [priority, setPriority] = useState('');
  const params = useMemo(() => ({ ...(search ? { search } : {}), ...(status ? { status } : {}), ...(priority ? { priority } : {}) }), [search, status, priority]);
  const tickets = useListTickets(params, { query: { queryKey: getListTicketsQueryKey(params) } });
  const [searchDraft, setSearchDraft] = useState('');
  const hasFilters = Boolean(search || status || priority);
  const clearFilters = () => { setSearch(''); setSearchDraft(''); setStatus(''); setPriority(''); };

  return (
    <div className="animate-rise-in space-y-7">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><SectionLabel>Operations / queue</SectionLabel><h1 className="text-[clamp(1.8rem,4vw,2.65rem)] font-extrabold tracking-[-.06em]">Ticket queue</h1><p className="mt-2 max-w-lg text-sm text-muted-foreground">Every open request, one clear next move. Search by person, issue, or ticket number.</p></div><Link href="/" className="inline-flex w-fit items-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-extrabold text-primary-foreground transition-transform hover:-translate-y-0.5" data-testid="link-create-ticket"><Plus size={15} /> New ticket</Link></div>
      <div className="rounded-2xl border border-border bg-card p-3 shadow-sm sm:p-4"><div className="flex flex-col gap-3 lg:flex-row"><form onSubmit={(event) => { event.preventDefault(); setSearch(searchDraft); }} className="relative flex-1"><Search size={16} className="absolute left-3.5 top-3.5 text-muted-foreground" /><input value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} placeholder="Search tickets..." className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-3 text-sm outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" data-testid="input-search-tickets" /></form><div className="flex flex-wrap gap-2"><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-input bg-background px-3 text-xs font-semibold outline-none focus:border-primary" data-testid="select-filter-status"><option value="">All statuses</option><option value="Open">Open</option><option value="In Progress">In progress</option><option value="Waiting">Waiting</option><option value="Resolved">Resolved</option></select><select value={priority} onChange={(event) => setPriority(event.target.value)} className="h-11 rounded-xl border border-input bg-background px-3 text-xs font-semibold outline-none focus:border-primary" data-testid="select-filter-priority"><option value="">All priorities</option><option value="Urgent">Urgent</option><option value="High">High</option><option value="Normal">Normal</option><option value="Low">Low</option></select><button className="inline-flex h-11 items-center gap-2 rounded-xl border border-input px-3 text-xs font-semibold text-muted-foreground hover:bg-secondary" onClick={clearFilters} disabled={!hasFilters} data-testid="button-clear-filters"><X size={14} /> Clear</button></div></div><div className="mt-3 flex items-center gap-3 border-t border-border/70 pt-3 font-mono text-[10px] uppercase tracking-[.12em] text-muted-foreground"><Filter size={13} /> {hasFilters ? 'Filtered view' : 'All requests'} <span className="text-border">·</span> {tickets.data?.length ?? '—'} results <button className="ml-auto inline-flex items-center gap-1.5 hover:text-foreground" onClick={() => window.print()} data-testid="button-export-tickets"><Download size={12} /> Export view</button></div></div>
      <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2"><SlidersHorizontal size={15} className="text-primary" /><h2 className="text-sm font-extrabold">All requests</h2></div><p className="mt-1 text-xs text-muted-foreground">Updated moments ago · sorted by recent activity</p></div><span className="hidden rounded-md bg-primary/10 px-2 py-1 font-mono text-[10px] uppercase tracking-[.1em] text-primary sm:block">Queue live</span></div><div className="hidden grid-cols-[minmax(0,1fr)_130px_120px_110px] gap-4 border-y border-border/70 bg-secondary/30 px-5 py-2.5 font-mono text-[9px] uppercase tracking-[.14em] text-muted-foreground sm:grid sm:px-6"><span>Issue</span><span>Status</span><span>Owner</span><span className="text-right">Updated</span></div>{tickets.isLoading ? <SkeletonRows count={6} /> : tickets.isError ? <ErrorState onRetry={() => tickets.refetch()} /> : tickets.data?.length ? tickets.data.map((ticket) => <TicketRow key={ticket.id} ticket={ticket} />) : <EmptyState title="No tickets match this view" detail="Try a wider search or clear the filters to see more of the queue." />}</div>
    </div>
  );
}